<?php

namespace Database\Seeders;

use App\Models\Skill;
use App\Models\Category;
use Illuminate\Database\Seeder;

class SkillSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $skills = [
            // Teknologi & Pemrograman
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Laravel'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'React'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Vue.js'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Angular'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'JavaScript'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'TypeScript'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Python'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'PHP'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Java'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Kotlin'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Swift'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'C'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'C++'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'C#'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Go'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Rust'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Ruby'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Ruby on Rails'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Flutter'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Dart'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'React Native'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Node.js'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Next.js'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Nuxt.js'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Express.js'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Django'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'FastAPI'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Flask'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Spring Boot'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'MySQL'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'PostgreSQL'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'MongoDB'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Redis'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Firebase'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Supabase'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Docker'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Kubernetes'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'AWS'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Google Cloud'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Azure'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Git'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'GitHub'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Linux'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Cyber Security'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Ethical Hacking'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'IoT'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Blockchain'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Web3'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Unity'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Unreal Engine'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Game Design'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Tailwind CSS'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Bootstrap'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'GraphQL'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'REST API'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Microservices'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'DevOps'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'CI/CD'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Terraform'],
            ['category' => 'Teknologi & Pemrograman', 'name' => 'Ansible'],

            // Desain Kreatif
            ['category' => 'Desain Kreatif', 'name' => 'Figma'],
            ['category' => 'Desain Kreatif', 'name' => 'Adobe XD'],
            ['category' => 'Desain Kreatif', 'name' => 'Sketch'],
            ['category' => 'Desain Kreatif', 'name' => 'UI Design'],
            ['category' => 'Desain Kreatif', 'name' => 'UX Design'],
            ['category' => 'Desain Kreatif', 'name' => 'UX Research'],
            ['category' => 'Desain Kreatif', 'name' => 'Wireframing'],
            ['category' => 'Desain Kreatif', 'name' => 'Prototyping'],
            ['category' => 'Desain Kreatif', 'name' => 'Canva'],
            ['category' => 'Desain Kreatif', 'name' => 'Photoshop'],
            ['category' => 'Desain Kreatif', 'name' => 'Illustrator'],
            ['category' => 'Desain Kreatif', 'name' => 'InDesign'],
            ['category' => 'Desain Kreatif', 'name' => 'CorelDraw'],
            ['category' => 'Desain Kreatif', 'name' => 'Blender'],
            ['category' => 'Desain Kreatif', 'name' => '3D Modeling'],
            ['category' => 'Desain Kreatif', 'name' => 'Motion Graphics'],
            ['category' => 'Desain Kreatif', 'name' => 'Typography'],
            ['category' => 'Desain Kreatif', 'name' => 'Branding Design'],
            ['category' => 'Desain Kreatif', 'name' => 'Logo Design'],
            ['category' => 'Desain Kreatif', 'name' => 'Poster Design'],
            ['category' => 'Desain Kreatif', 'name' => 'Infographic'],
            ['category' => 'Desain Kreatif', 'name' => 'Design System'],
            ['category' => 'Desain Kreatif', 'name' => 'Design Thinking'],
            ['category' => 'Desain Kreatif', 'name' => 'Procreate'],
            ['category' => 'Desain Kreatif', 'name' => 'Spline'],
            ['category' => 'Desain Kreatif', 'name' => 'Webflow'],
            ['category' => 'Desain Kreatif', 'name' => 'Framer'],

            // Data & AI
            ['category' => 'Data & AI', 'name' => 'Excel'],
            ['category' => 'Data & AI', 'name' => 'Google Sheets'],
            ['category' => 'Data & AI', 'name' => 'SQL'],
            ['category' => 'Data & AI', 'name' => 'Power BI'],
            ['category' => 'Data & AI', 'name' => 'Tableau'],
            ['category' => 'Data & AI', 'name' => 'Looker Studio'],
            ['category' => 'Data & AI', 'name' => 'Data Analysis'],
            ['category' => 'Data & AI', 'name' => 'Data Visualization'],
            ['category' => 'Data & AI', 'name' => 'Data Science'],
            ['category' => 'Data & AI', 'name' => 'Machine Learning'],
            ['category' => 'Data & AI', 'name' => 'Deep Learning'],
            ['category' => 'Data & AI', 'name' => 'Natural Language Processing'],
            ['category' => 'Data & AI', 'name' => 'Computer Vision'],
            ['category' => 'Data & AI', 'name' => 'TensorFlow'],
            ['category' => 'Data & AI', 'name' => 'PyTorch'],
            ['category' => 'Data & AI', 'name' => 'Scikit-learn'],
            ['category' => 'Data & AI', 'name' => 'Pandas'],
            ['category' => 'Data & AI', 'name' => 'NumPy'],
            ['category' => 'Data & AI', 'name' => 'Jupyter Notebook'],
            ['category' => 'Data & AI', 'name' => 'R'],
            ['category' => 'Data & AI', 'name' => 'Statistics'],
            ['category' => 'Data & AI', 'name' => 'Big Data'],
            ['category' => 'Data & AI', 'name' => 'Hadoop'],
            ['category' => 'Data & AI', 'name' => 'Spark'],
            ['category' => 'Data & AI', 'name' => 'AI Prompt Engineering'],

            // Bahasa
            ['category' => 'Bahasa', 'name' => 'English'],
            ['category' => 'Bahasa', 'name' => 'Japanese'],
            ['category' => 'Bahasa', 'name' => 'Korean'],
            ['category' => 'Bahasa', 'name' => 'Mandarin'],
            ['category' => 'Bahasa', 'name' => 'Arabic'],
            ['category' => 'Bahasa', 'name' => 'French'],
            ['category' => 'Bahasa', 'name' => 'German'],
            ['category' => 'Bahasa', 'name' => 'Spanish'],
            ['category' => 'Bahasa', 'name' => 'Italian'],
            ['category' => 'Bahasa', 'name' => 'Portuguese'],
            ['category' => 'Bahasa', 'name' => 'Dutch'],
            ['category' => 'Bahasa', 'name' => 'Russian'],
            ['category' => 'Bahasa', 'name' => 'Hindi'],
            ['category' => 'Bahasa', 'name' => 'Thai'],
            ['category' => 'Bahasa', 'name' => 'Vietnamese'],
            ['category' => 'Bahasa', 'name' => 'Malay'],
            ['category' => 'Bahasa', 'name' => 'Turkish'],
            ['category' => 'Bahasa', 'name' => 'Sign Language'],
            ['category' => 'Bahasa', 'name' => 'IELTS'],
            ['category' => 'Bahasa', 'name' => 'TOEFL'],
            ['category' => 'Bahasa', 'name' => 'JLPT'],
            ['category' => 'Bahasa', 'name' => 'TOPIK'],
            ['category' => 'Bahasa', 'name' => 'HSK'],

            // Bisnis & Marketing
            ['category' => 'Bisnis & Marketing', 'name' => 'SEO'],
            ['category' => 'Bisnis & Marketing', 'name' => 'SEM'],
            ['category' => 'Bisnis & Marketing', 'name' => 'Copywriting'],
            ['category' => 'Bisnis & Marketing', 'name' => 'Content Writing'],
            ['category' => 'Bisnis & Marketing', 'name' => 'Digital Marketing'],
            ['category' => 'Bisnis & Marketing', 'name' => 'Social Media Marketing'],
            ['category' => 'Bisnis & Marketing', 'name' => 'Email Marketing'],
            ['category' => 'Bisnis & Marketing', 'name' => 'Google Ads'],
            ['category' => 'Bisnis & Marketing', 'name' => 'Facebook Ads'],
            ['category' => 'Bisnis & Marketing', 'name' => 'Instagram Ads'],
            ['category' => 'Bisnis & Marketing', 'name' => 'TikTok Ads'],
            ['category' => 'Bisnis & Marketing', 'name' => 'Branding'],
            ['category' => 'Bisnis & Marketing', 'name' => 'Entrepreneurship'],
            ['category' => 'Bisnis & Marketing', 'name' => 'Business Plan'],
            ['category' => 'Bisnis & Marketing', 'name' => 'Financial Planning'],
            ['category' => 'Bisnis & Marketing', 'name' => 'Accounting'],
            ['category' => 'Bisnis & Marketing', 'name' => 'E-commerce'],
            ['category' => 'Bisnis & Marketing', 'name' => 'Dropshipping'],
            ['category' => 'Bisnis & Marketing', 'name' => 'Affiliate Marketing'],
            ['category' => 'Bisnis & Marketing', 'name' => 'Product Management'],
            ['category' => 'Bisnis & Marketing', 'name' => 'Project Management'],
            ['category' => 'Bisnis & Marketing', 'name' => 'Scrum'],
            ['category' => 'Bisnis & Marketing', 'name' => 'Agile'],
            ['category' => 'Bisnis & Marketing', 'name' => 'Market Research'],
            ['category' => 'Bisnis & Marketing', 'name' => 'Sales'],

            // Musik & Audio
            ['category' => 'Musik & Audio', 'name' => 'Gitar Akustik'],
            ['category' => 'Musik & Audio', 'name' => 'Gitar Elektrik'],
            ['category' => 'Musik & Audio', 'name' => 'Gitar Bass'],
            ['category' => 'Musik & Audio', 'name' => 'Piano'],
            ['category' => 'Musik & Audio', 'name' => 'Keyboard'],
            ['category' => 'Musik & Audio', 'name' => 'Drum'],
            ['category' => 'Musik & Audio', 'name' => 'Vokal'],
            ['category' => 'Musik & Audio', 'name' => 'Biola'],
            ['category' => 'Musik & Audio', 'name' => 'Saxophone'],
            ['category' => 'Musik & Audio', 'name' => 'Trumpet'],
            ['category' => 'Musik & Audio', 'name' => 'Ukulele'],
            ['category' => 'Musik & Audio', 'name' => 'DJ'],
            ['category' => 'Musik & Audio', 'name' => 'Music Production'],
            ['category' => 'Musik & Audio', 'name' => 'FL Studio'],
            ['category' => 'Musik & Audio', 'name' => 'Ableton Live'],
            ['category' => 'Musik & Audio', 'name' => 'GarageBand'],
            ['category' => 'Musik & Audio', 'name' => 'Logic Pro'],
            ['category' => 'Musik & Audio', 'name' => 'Mixing & Mastering'],
            ['category' => 'Musik & Audio', 'name' => 'Sound Design'],
            ['category' => 'Musik & Audio', 'name' => 'Podcast'],
            ['category' => 'Musik & Audio', 'name' => 'Audio Editing'],
            ['category' => 'Musik & Audio', 'name' => 'Audacity'],
            ['category' => 'Musik & Audio', 'name' => 'Voice Over'],
            ['category' => 'Musik & Audio', 'name' => 'Beatmaking'],
            ['category' => 'Musik & Audio', 'name' => 'Music Theory'],

            // Fotografi & Video
            ['category' => 'Fotografi & Video', 'name' => 'Photography'],
            ['category' => 'Fotografi & Video', 'name' => 'Portrait Photography'],
            ['category' => 'Fotografi & Video', 'name' => 'Landscape Photography'],
            ['category' => 'Fotografi & Video', 'name' => 'Product Photography'],
            ['category' => 'Fotografi & Video', 'name' => 'Street Photography'],
            ['category' => 'Fotografi & Video', 'name' => 'Wedding Photography'],
            ['category' => 'Fotografi & Video', 'name' => 'Videography'],
            ['category' => 'Fotografi & Video', 'name' => 'Cinematography'],
            ['category' => 'Fotografi & Video', 'name' => 'Video Editing'],
            ['category' => 'Fotografi & Video', 'name' => 'Premiere Pro'],
            ['category' => 'Fotografi & Video', 'name' => 'After Effects'],
            ['category' => 'Fotografi & Video', 'name' => 'DaVinci Resolve'],
            ['category' => 'Fotografi & Video', 'name' => 'CapCut'],
            ['category' => 'Fotografi & Video', 'name' => 'Final Cut Pro'],
            ['category' => 'Fotografi & Video', 'name' => 'Lightroom'],
            ['category' => 'Fotografi & Video', 'name' => 'Color Grading'],
            ['category' => 'Fotografi & Video', 'name' => 'Drone Photography'],
            ['category' => 'Fotografi & Video', 'name' => 'Stop Motion'],
            ['category' => 'Fotografi & Video', 'name' => 'Animation 2D'],
            ['category' => 'Fotografi & Video', 'name' => 'Animation 3D'],
            ['category' => 'Fotografi & Video', 'name' => 'YouTube Content'],
            ['category' => 'Fotografi & Video', 'name' => 'TikTok Content'],
            ['category' => 'Fotografi & Video', 'name' => 'Instagram Reels'],
            ['category' => 'Fotografi & Video', 'name' => 'Vlogging'],
            ['category' => 'Fotografi & Video', 'name' => 'Live Streaming'],

            // Seni & Kreativitas
            ['category' => 'Seni & Kreativitas', 'name' => 'Drawing'],
            ['category' => 'Seni & Kreativitas', 'name' => 'Sketching'],
            ['category' => 'Seni & Kreativitas', 'name' => 'Ilustrasi Digital'],
            ['category' => 'Seni & Kreativitas', 'name' => 'Melukis'],
            ['category' => 'Seni & Kreativitas', 'name' => 'Watercolor'],
            ['category' => 'Seni & Kreativitas', 'name' => 'Oil Painting'],
            ['category' => 'Seni & Kreativitas', 'name' => 'Acrylic Painting'],
            ['category' => 'Seni & Kreativitas', 'name' => 'Kaligrafi'],
            ['category' => 'Seni & Kreativitas', 'name' => 'Hand Lettering'],
            ['category' => 'Seni & Kreativitas', 'name' => 'Comic & Manga'],
            ['category' => 'Seni & Kreativitas', 'name' => 'Character Design'],
            ['category' => 'Seni & Kreativitas', 'name' => 'Concept Art'],
            ['category' => 'Seni & Kreativitas', 'name' => 'Sculpting'],
            ['category' => 'Seni & Kreativitas', 'name' => 'Pottery'],
            ['category' => 'Seni & Kreativitas', 'name' => 'Origami'],
            ['category' => 'Seni & Kreativitas', 'name' => 'Craft'],
            ['category' => 'Seni & Kreativitas', 'name' => 'Fashion Design'],
            ['category' => 'Seni & Kreativitas', 'name' => 'Interior Design'],
            ['category' => 'Seni & Kreativitas', 'name' => 'Architecture'],
            ['category' => 'Seni & Kreativitas', 'name' => 'Creative Writing'],
            ['category' => 'Seni & Kreativitas', 'name' => 'Puisi'],
            ['category' => 'Seni & Kreativitas', 'name' => 'Novel Writing'],
            ['category' => 'Seni & Kreativitas', 'name' => 'Screenwriting'],
            ['category' => 'Seni & Kreativitas', 'name' => 'Acting'],
            ['category' => 'Seni & Kreativitas', 'name' => 'Dance'],

            // Olahraga
            ['category' => 'Olahraga', 'name' => 'Futsal'],
            ['category' => 'Olahraga', 'name' => 'Sepak Bola'],
            ['category' => 'Olahraga', 'name' => 'Badminton'],
            ['category' => 'Olahraga', 'name' => 'Basket'],
            ['category' => 'Olahraga', 'name' => 'Voli'],
            ['category' => 'Olahraga', 'name' => 'Tenis'],
            ['category' => 'Olahraga', 'name' => 'Tenis Meja'],
            ['category' => 'Olahraga', 'name' => 'Renang'],
            ['category' => 'Olahraga', 'name' => 'Gym'],
            ['category' => 'Olahraga', 'name' => 'Yoga'],
            ['category' => 'Olahraga', 'name' => 'Pilates'],
            ['category' => 'Olahraga', 'name' => 'Lari'],
            ['category' => 'Olahraga', 'name' => 'Bersepeda'],
            ['category' => 'Olahraga', 'name' => 'Hiking'],
            ['category' => 'Olahraga', 'name' => 'Climbing'],
            ['category' => 'Olahraga', 'name' => 'Martial Arts'],
            ['category' => 'Olahraga', 'name' => 'Taekwondo'],
            ['category' => 'Olahraga', 'name' => 'Karate'],
            ['category' => 'Olahraga', 'name' => 'Silat'],
            ['category' => 'Olahraga', 'name' => 'Boxing'],
            ['category' => 'Olahraga', 'name' => 'Skateboard'],
            ['category' => 'Olahraga', 'name' => 'Surfing'],
            ['category' => 'Olahraga', 'name' => 'E-Sport'],
            ['category' => 'Olahraga', 'name' => 'Chess'],
            ['category' => 'Olahraga', 'name' => 'Golf'],

            // Soft Skill
            ['category' => 'Soft Skill', 'name' => 'Public Speaking'],
            ['category' => 'Soft Skill', 'name' => 'Presentasi'],
            ['category' => 'Soft Skill', 'name' => 'Leadership'],
            ['category' => 'Soft Skill', 'name' => 'Teamwork'],
            ['category' => 'Soft Skill', 'name' => 'Komunikasi'],
            ['category' => 'Soft Skill', 'name' => 'Negosiasi'],
            ['category' => 'Soft Skill', 'name' => 'Problem Solving'],
            ['category' => 'Soft Skill', 'name' => 'Critical Thinking'],
            ['category' => 'Soft Skill', 'name' => 'Creative Thinking'],
            ['category' => 'Soft Skill', 'name' => 'Time Management'],
            ['category' => 'Soft Skill', 'name' => 'Self Management'],
            ['category' => 'Soft Skill', 'name' => 'Adaptability'],
            ['category' => 'Soft Skill', 'name' => 'Emotional Intelligence'],
            ['category' => 'Soft Skill', 'name' => 'Conflict Resolution'],
            ['category' => 'Soft Skill', 'name' => 'Decision Making'],
            ['category' => 'Soft Skill', 'name' => 'Networking'],
            ['category' => 'Soft Skill', 'name' => 'Mentoring'],
            ['category' => 'Soft Skill', 'name' => 'Coaching'],
            ['category' => 'Soft Skill', 'name' => 'Facilitation'],
            ['category' => 'Soft Skill', 'name' => 'Research'],
            ['category' => 'Soft Skill', 'name' => 'Writing'],
            ['category' => 'Soft Skill', 'name' => 'Storytelling'],
            ['category' => 'Soft Skill', 'name' => 'Debating'],
            ['category' => 'Soft Skill', 'name' => 'Fundraising'],
            ['category' => 'Soft Skill', 'name' => 'Event Organizing'],

            // Akademik
            ['category' => 'Akademik', 'name' => 'Matematika'],
            ['category' => 'Akademik', 'name' => 'Statistika'],
            ['category' => 'Akademik', 'name' => 'Kalkulus'],
            ['category' => 'Akademik', 'name' => 'Aljabar Linear'],
            ['category' => 'Akademik', 'name' => 'Fisika'],
            ['category' => 'Akademik', 'name' => 'Kimia'],
            ['category' => 'Akademik', 'name' => 'Biologi'],
            ['category' => 'Akademik', 'name' => 'Ekonomi'],
            ['category' => 'Akademik', 'name' => 'Akuntansi'],
            ['category' => 'Akademik', 'name' => 'Manajemen'],
            ['category' => 'Akademik', 'name' => 'Hukum'],
            ['category' => 'Akademik', 'name' => 'Psikologi'],
            ['category' => 'Akademik', 'name' => 'Sosiologi'],
            ['category' => 'Akademik', 'name' => 'Filsafat'],
            ['category' => 'Akademik', 'name' => 'Sejarah'],
            ['category' => 'Akademik', 'name' => 'Geografi'],
            ['category' => 'Akademik', 'name' => 'Astronomi'],
            ['category' => 'Akademik', 'name' => 'Teknik Sipil'],
            ['category' => 'Akademik', 'name' => 'Teknik Mesin'],
            ['category' => 'Akademik', 'name' => 'Teknik Elektro'],
            ['category' => 'Akademik', 'name' => 'Teknik Kimia'],
            ['category' => 'Akademik', 'name' => 'Kedokteran'],
            ['category' => 'Akademik', 'name' => 'Keperawatan'],
            ['category' => 'Akademik', 'name' => 'Farmasi'],
            ['category' => 'Akademik', 'name' => 'Gizi'],
        ];

        foreach ($skills as $skill) {
            $category = Category::where('name', $skill['category'])->first();
            Skill::create([
                'category_id' => $category->id,
                'name'        => $skill['name'],
            ]);
        }
    }
}